language: python
install:
- pip3 install flask
script:
- python3 ./flaskapp/some_app.py
language: python
before_install:
- chmod +x ./flaskapp/st.sh
install:
- pip3 install flask
- pip3 install gunicorn
script:
- cd flaskapp
- ./st.sh
